### ISSUE TITLE
google.protobuf.Timestamp needs to be converted to string in schema instead of an object

### ISSUE THREAD

**Issue by xliiauo** [chrusty/protoc-gen-jsonschema#11]
In https://developers.google.com/protocol-buffers/docs/proto3#json , the correct type for a Timestamp in JSON is string instead of an object. When using protoc-gen-jsonschema, `google.protobuf.Timestamp` will create:
```
"timestamp": {
    "properties": {
        "nanos": {
            "type": "integer"
        },
        "seconds": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "string"
                }
            ]
        }
    },
    "additionalProperties": true,
    "type": "object"
},
```
instead, it should be string:
```
"timestamp": {
    "type": "string"
},
```
please can you fix, thank you very much.

**Comment by huttotw** [comment]
We are having this issue as well, I am planning to hack on this today to see if I can get it to work.

**Comment by huttotw** [comment]
Pull request in to fix this (#12). Will output `google/protobuf/timestamp.proto` like:
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "timestamp": {
            "type": "string",
            "format": "date-time"
        }
    },
    "additionalProperties": true,
    "type": "object"
}
```

**Comment by chrusty** [comment]
Hi @huttotw and @xliiauo, thanks for your interest. Sorry I don't get around to checking this very often.

I think we may have to support several formats for timestamps here, because in my experience different JSON marshalers will give different results.

For example, the "correct" marshaling _should_ give a timestamp as a string, but naive marshaling would result in seconds and nanos. I'm guessing the best way would be to handle both.

**Comment by sttawm** [comment]
I don't think there's ambiguity in the format of the timestamp.

As per the protobuf authors:

> // # JSON Mapping
//
// In JSON format, the Timestamp type is encoded as a string in the
// [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
// format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
// where {year} is always expressed using four digits while {month}, {day},
// {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
// seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
// are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
// is required. A proto3 JSON serializer should always use UTC (as indicated by
// "Z") when printing the Timestamp type and a proto3 JSON parser should be
// able to accept both UTC and other timezones (as indicated by an offset).
//
// For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
// 01:30 UTC on January 15, 2017.
//
// In JavaScript, one can convert a Date object to this format using the
// standard
// [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
// method. In Python, a standard `datetime.datetime` object can be converted
// to this format using
// [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
// the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
// the Joda Time's [`ISODateTimeFormat.dateTime()`](
// http://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime%2D%2D
// ) to obtain a formatter capable of generating timestamps in this format.

~ https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto

Anyway, I don't think validating as a string instead of object is a bad idea. It's not as strict as it should be (^ see above), but at least it handles a properly formatted timestamp correctly.

**Comment by chrusty** [comment]
@huttotw I raised a new PR copied from your original one (was unable to merge your one because the layout of the project has changed significantly since then).

https://github.com/chrusty/protoc-gen-jsonschema/pull/25

It doesn't break any of the existing unit tests so I guess we should be fine, but I'd like to run it by a few other people first.

**Comment by chrusty** [comment]
@huttotw, @sttawm , @xliiauo I've merged this in now, and created a new release. Thanks for your comments!

https://github.com/chrusty/protoc-gen-jsonschema/releases/tag/0.9.0
