### ISSUE TITLE
Option to ignore deprecated proto fields

### ISSUE THREAD

**Issue by aurc** [chrusty/protoc-gen-jsonschema#123]
Hello,

Nice lib! Is there any plans to add an option to ignore deprecated fields on generation, e.g.:
````
message MyProtoType {
  string id = 1;
  repeated string name = 2; 
  repeated Bar bar = 3 [deprecated=true];
  repeated Foo foo = 4;
}
````

An option like `ignore-deprecated` would be very useful !

**Comment by chrusty** [comment]
Hello @aurc, funny you should bring this topic up. Back when I was implementing the facility to _ignore_ fields I originally considered using the `deprecated=true` flag to mark ignored fields. This was mainly because I was being lazy, was trying to avoid implementing my own proto options.

In the end I DID implement my own proto options however, and they're working quite nicely. Does your situation allow you to use the custom proto options in this circumstance?

**Comment by chrusty** [comment]
I'll close this down for now, feel free to oepn it up again if we've not solved the issue @aurc
