### ISSUE TITLE
Reference to an enum in an ignored file

### ISSUE THREAD

**Issue by seinshah** [chrusty/protoc-gen-jsonschema#124]
I have a package with two files where in file B, I refer to file A's enum type. I have added `option (protoc.gen.jsonschema.file_options).ignore = true;` to file A. E.g.

`A.proto`
```
syntax = "proto3";

package x.y.z;

option (protoc.gen.jsonschema.file_options).ignore = true;

enum X {
  X_1 = 1;
}
```

`B.proto`
```
syntax = "proto3";

package x.y.z

import "..../A.proto"

message Y {
  X my_attr = 1;
}
```

**Expected Behavior**
I expect that plugin access the enum in the other file regardless of the file option in that file as it has been referred to in file B.

**Actual Behavior**
When trying to generate schemas, I receive:

```
Failed to convert ../B.proto: unable to resolve enum type: TYPE_ENUM
```

**Workaround**
If I remove the file option in A.proto and add message option to all the messages (as I don't want schema for them), it works properly. Also if I remove all the file and message options from A.proto and provide the message name in the generator config, it works as well.

However, due to my usecase I prefer the expected behavior above. Is this in-line with this plugin's plans?

**Comment by chrusty** [comment]
Hello @seinshah. I'm sorry, but the "ignore file" option is very basic - if the plugin encounters that then it simply moves on with the next file (which is kind of the point).

I think your options here look like this:

- remove the ignore option from file A OR
- move the enum declaration to a new `C.proto` and include that OR
- instead of using the ignore _file_ option you could use the ignore _message_ option to filter out the specific messages in A.proto that you don't want (though at the moment there is no ignore option for ENUMs, which may be a useful thing for me to add)

I know this is not the solution you're after, but at least there _are_ 3 workable options here. Let me know if you'd be interested in the ignore-enum option.

Thanks for raising this, and thank you for your interest in the project. My apologies for taking so long to respond!

**Comment by chrusty** [comment]
@seinshah I've added an option to ignore specific enums now. This is not yet released, but in the `master` branch. Please let me know if this solves your problem

**Comment by chrusty** [comment]
I'll close this down for now, feel free to oepn it up again if we've not solved the issue @seinshah
