### ISSUE TITLE
expose internal package

### ISSUE THREAD

**Issue by tmc** [chrusty/protoc-gen-jsonschema#163]
why place the conversion code in internal/ others may benefit from it being importable

**Comment by chrusty** [comment]
Hi @tmc, good question there. The reason is that `internal` packages imply that there is no stable API / interface. This gives me the freedom to refactor the internals safe in the knowledge that I'm not going to break anyone's imports. That's the idea anyway.

There is nothing stopping us from exposing certain things as importable packages elsewhere, but that would become another thing to maintain.

You're not the first person to raise this question, and actually I agree that it would be useful to expose the conversion logic as public methods. Probably the biggest issue is the interface i have to adhere to as a protoc plugin. GoLang has (to my knowledge at least) no native way to read a proto file - this is handled by the `protoc` binary itself. Believe me if there was a way then I'd like to know about it - this is why the unit tests for protoc-gen-jsonschema call out to the protoc binary!

So yeah in its current state the converter logic wouldn't be much use because putting those request parameters together by-hand is an overwhelming task.

I hope this helps to explain the rationale.
