### ISSUE TITLE
Cannot compile when two messages have the same name

### ISSUE THREAD

**Issue by Kiyo5hi** [chrusty/protoc-gen-jsonschema#85]
I've defined two protos with exactly the same content, but in different folders as such:

```tree
proto/
├─ a/
│  ├─ pet.proto
├─ b/
│  ├─ pet.proto
```

As I expect the output should be in the same structure as shown above just like when using `--python_out` or other options, `protoc` throws `Tried to write the same file twice.`

Even if I rename one of the messages to `message Pet1`, the output structure is flat, like so:

```tree
schema/
├─ Pet.jsonschema
├─ Pet1.jsonschema
```

Should that be fixed? Cuz reading and writing files recursively should be a feature.

**Comment by chrusty** [comment]
Hello @Kiyo5hi, and thanks for your interest in the project.

In your example, are your proto files separated into different packages? Proto packages are namespaced, and protoc-gen-jsonschema produces one file per message.

Eg is a/pet.proto in a package called "a", and b/pet.proto in a package with a different name like "b"?

If so, then you could look at using the `prefix_schema_files_with_package` option. This would actually result in the generated jsonschema files being in different directories (matching your proto package structure). This option was introduced a long time ago and probably doesn't get a lot of use, but it might just be the thing you need! You will see an example of this [here](https://github.com/chrusty/protoc-gen-jsonschema#prefix-generated-schema-files-with-their-package-name-as-a-directory).

Please let me know how you get on with this!

Otherwise you could consider just running protoc more than once (once against the A directory, then a second time against the B directory (though I'm not entirely sure of your use-case of course).

**Comment by Kiyo5hi** [comment]
That does the math for me; thank you! BTW, how do I apply multiple options at once?

**Comment by chrusty** [comment]
I'm pleased to hear that works!

Use multiple options with this syntax:

`protoc --jsonschema_out=prefix_schema_files_with_package,all_fields_required:. `

**Comment by chrusty** [comment]
(Separated by comma)
